version: "3.3"

services:
    db:
      image: postgres:9.6
      volumes:
        - db_data:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: catalogo-cinemas
      networks:
        - the_net

    web:
      depends_on:
        - db
      build: ./docker/web
      image: brunocarvalho287/manutencao-20182:latest
      ports:
        - "8080:8080"
      networks:
        - the_net

volumes:
    db_data:

networks:
  the_net:
    driver: bridge
