version: 2.0
jobs:
    build:
      docker:
        - image: maven:3.5.0-jdk-8
          environment:
            JDBC_DATABASE_URL: jdbc:postgresql://127.0.0.1:5432/manutencao20182
            JDBC_DATABASE_USERNAME: manutencao
            JDBC_DATABASE_PASSWORD: manutencao
        - image: postgres:9.6
  
      working_directory: ~/repo

      steps:
        - checkout
        - run: apt-get update -qq && apt-get install -y postgresql
        - run:
            command: |
              psql -h 127.0.0.1 -U postgres -c "CREATE DATABASE manutencao20182;"
              psql -h 127.0.0.1 -U postgres -c "CREATE USER manutencao WITH PASSWORD 'manutencao'; GRANT ALL PRIVILEGES ON DATABASE manutencao20182 TO manutencao;"
        - restore_cache:
                keys:
                - v1-dependencies-{{checksum "pom.xml"}}
                - v1-dependencies
        - run: mvn dependency:go-offline
        - run: 
            command: mvn package
        - store_test_results: # uploads the test metadata from the `target/surefire-reports` directory so that it can show up in the CircleCI dashboard.
            path: target/surefire-reports
        - save_cache:
            paths: ~/.m2
            key: v1-dependencies-{{checksum "pom.xml"}}
        - run: cd target
        - run: ls -la
        - store_artifacts:
            path: target/catalogo-cinemas.war
        # - persist_to_workspace:
        #         <<: *source

    deploy:
      docker:
        - image: buildpack-deps:trusty
      steps:
        - checkout
        - run:
            name: Deploy to heroku
            command: |
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build