version: 2.0
jobs:
    build:
      docker:
        - image: circleci/openjdk:8-jdk
        - image: postgres:9.6
      steps:
        - checkout
        - restore_cache:
                keys:
                - v1-dependencies-{{checksum "pom.xml"}}
                - v1-dependencies
        - run: mvn dependency:go-offline
        - run: 
            command: mvn package
            environment:
              JDBC_DATABASE_URL: $DATABASE_URL
              JDBC_DATABASE_USERNAME: $DATABASE_USERNAME
              JDBC_DATABASE_PASSWORD: $DATABASE_PASSWORD
        - store_test_results: # uploads the test metadata from the `target/surefire-reports` directory so that it can show up in the CircleCI dashboard.
                path: target/surefire-reports
        - save_cache:
                paths: ~/.m2
                key: v1-dependencies-{{checksum "pom.xml"}}
        # - persist_to_workspace:
        #         <<: *source

    deploy:
      docker:
        - image: buildpack-deps:trusty
      steps:
        - checkout
        - run:
            name: Deploy to heroku
            command: |
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build